### ISSUE TITLE
No documentation on how to use this tool

### ISSUE THREAD

**Issue by bnriiitb** [AI4Bharat/Chitralekha#2]
Can you add documentation on how to use this tool?

**Comment by aravinth** [comment]
Hi. We have created a demo video on how to the tool : 
https://youtu.be/yNuRFJ1fCsw

Please share your feedback..

**Comment by bnriiitb** [comment]
@aravinth  Thanks for the vide. The video that you shared doesn't have any instructions around setting up the tool. Can you share the steps/instructions to run this tool on local or set it up on the server?

**Comment by aravinth** [comment]
Please go through https://github.com/AI4Bharat/Chitralekha/wiki/Tool-Setup and let us know if this documentation needs to be improved.
